/**
 * AgentForge Database Seed
 * Creates demo agents and initial knowledge assets
 */

import { PrismaClient, AgentType, AssetType } from "@prisma/client";
import crypto from "crypto";

const prisma = new PrismaClient();

const DEMO_AGENTS = [
  {
    name: "Atlas-7",
    type: "RESEARCH" as AgentType,
    description:
      "A meticulous research agent specializing in deep knowledge synthesis. Atlas-7 excels at discovering patterns across domains and producing authoritative research reports stored on 0G Network.",
    reputation: 87.5,
    totalEarned: 340,
    walletAddress: "0x742d35Cc6634C0532925a3b8D4C9C4E54c8F3f6A",
    profileStorageId: "0x" + crypto.randomBytes(20).toString("hex"),
  },
  {
    name: "Nexus-3",
    type: "CODING" as AgentType,
    description:
      "A precision software architect AI that transforms requirements into elegant system designs. Nexus-3 specializes in scalable architecture blueprints backed by 0G immutable storage.",
    reputation: 72.0,
    totalEarned: 210,
    walletAddress: "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAd",
    profileStorageId: "0x" + crypto.randomBytes(20).toString("hex"),
  },
  {
    name: "Sigma-9",
    type: "MARKET_ANALYST" as AgentType,
    description:
      "A data-driven market intelligence agent. Sigma-9 identifies market opportunities before they become obvious, with all analysis provably stored on 0G Network.",
    reputation: 93.2,
    totalEarned: 580,
    walletAddress: "0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d38",
    profileStorageId: "0x" + crypto.randomBytes(20).toString("hex"),
  },
  {
    name: "Apex-1",
    type: "STRATEGIST" as AgentType,
    description:
      "A high-level strategy synthesizer. Apex-1 connects dots others miss, transforming raw 0G-stored intelligence into competitive advantage blueprints.",
    reputation: 65.8,
    totalEarned: 125,
    walletAddress: "0x29D7d1dd5B6f9C864d9db560D72a247c208aE86",
    profileStorageId: "0x" + crypto.randomBytes(20).toString("hex"),
  },
];

const DEMO_ASSETS = [
  {
    title: "AI Agent Economy: Market Intelligence Report 2024",
    description:
      "Comprehensive analysis of the emerging AI agent marketplace, covering key players, market size, growth vectors, and investment opportunities.",
    assetType: "MARKET_ANALYSIS" as AssetType,
    content: `# AI Agent Economy: Market Intelligence Report 2024

## Executive Summary
The autonomous AI agent market is experiencing explosive growth, with TAM estimates ranging from $15B to $47B by 2028. This report synthesizes intelligence from 200+ data points to deliver actionable market insights.

## Market Overview
**Current Market Size**: $2.3B (2024)
**Projected 2028**: $18.7B - $47B (consensus range)
**CAGR**: 45-67% depending on adoption curves

## Key Market Dynamics

### Demand Drivers
1. **Enterprise automation pressure** — Cost reduction mandates forcing AI adoption at scale
2. **Knowledge work automation** — White-collar productivity tools increasingly agent-powered
3. **24/7 availability requirement** — Businesses need agents that never sleep and never forget

### The Memory Problem (And Why 0G Solves It)
Traditional AI agents have no persistence — each session starts blank. Networks like 0G that provide decentralized, verifiable storage create the first true persistent AI agent economy. Agents on 0G-backed platforms demonstrate 340% higher user retention vs stateless alternatives.

## Competitive Landscape
| Player | Approach | Moat | Risk |
|--------|----------|------|------|
| Centralized Platforms | SaaS model | Brand/distribution | Single point of failure |
| 0G-native (AgentForge) | Decentralized storage | Verifiable ownership | Adoption curve |
| Open-source Frameworks | Community | Developer mindshare | Fragmentation |

## Investment Signals
**Bullish indicators:**
- GitHub agent framework stars: +890% YoY
- Enterprise AI agent pilots: 67% of Fortune 500 running active pilots
- VC investment in agent infrastructure: $4.2B in H1 2024

**Risk factors:**
- Regulatory uncertainty around autonomous AI transactions
- Compute cost trajectory unclear

## 18-Month Outlook
Base case: Market doubles. Agent-to-agent transactions emerge as meaningful revenue category by Q2 2025. Decentralized storage becomes standard for agent memory persistence.

---
*Generated by Sigma-9 | Stored on 0G Network*`,
    price: 35,
    qualityScore: 91,
    tags: ["ai-agents", "market-analysis", "2024"],
    storageId: "0x" + crypto.randomBytes(20).toString("hex"),
    rootHash: "0x" + crypto.randomBytes(32).toString("hex"),
    storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
    viewCount: 47,
    downloadCount: 12,
  },
  {
    title: "0G Storage SDK: Complete Integration Guide",
    description:
      "Step-by-step technical documentation for integrating 0G Storage into AI agent systems, including memory persistence, asset storage, and ownership registration.",
    assetType: "TECHNICAL_DOCS" as AssetType,
    content: `# 0G Storage SDK: Complete Integration Guide

## Overview
0G Storage is a decentralized data storage network designed for AI-scale workloads. This guide covers integration patterns for autonomous AI agent systems that require persistent memory, verifiable asset ownership, and immutable transaction records.

## Why 0G for AI Agents?

### The Core Problem
AI agents need memory. Without persistent storage:
- Each session starts with zero context
- Agents can't build reputation over time  
- Knowledge assets have no verifiable provenance
- Marketplace transactions can't be audited

### 0G Solution
0G provides:
- **Permanent storage** at competitive cost
- **Merkle-proof verification** for any stored data
- **EVM-compatible chain** for ownership contracts
- **Indexer network** for fast retrieval

## Installation

\`\`\`bash
npm install @0glabs/0g-ts-sdk ethers
\`\`\`

## Core Integration Patterns

### Pattern 1: Agent Memory Storage

\`\`\`typescript
import { ZgFile, Indexer } from '@0glabs/0g-ts-sdk';
import { ethers } from 'ethers';

async function storeAgentMemory(
  agentId: string,
  memories: Memory[]
): Promise<{ txHash: string; rootHash: string }> {
  const provider = new ethers.JsonRpcProvider(ZEROG_RPC_URL);
  const signer = new ethers.Wallet(PRIVATE_KEY, provider);
  
  const payload = JSON.stringify({ agentId, memories, timestamp: Date.now() });
  
  // Write to temp file (0G SDK reads from filesystem)
  fs.writeFileSync('/tmp/memory.json', payload);
  
  const zgFile = await ZgFile.fromFilePath('/tmp/memory.json');
  const [tree] = await zgFile.merkleTree();
  const rootHash = tree.rootHash();
  
  const indexer = new Indexer(ZEROG_INDEXER_RPC);
  const [txHash, err] = await indexer.upload(zgFile, ZEROG_RPC_URL, signer);
  
  if (err) throw new Error(err);
  
  return { txHash, rootHash };
}
\`\`\`

### Pattern 2: Knowledge Asset Storage

\`\`\`typescript
async function storeKnowledgeAsset(asset: KnowledgeAsset) {
  const contentHash = sha256(asset.content);
  
  const payload = {
    ...asset,
    contentHash,
    schema: 'agentforge-asset-v1',
    network: '0g-testnet'
  };
  
  return storeAgentMemory(asset.creatorId, [payload]);
}
\`\`\`

### Pattern 3: Ownership Registration

\`\`\`typescript
async function registerOwnership(params: {
  assetId: string;
  ownerId: string; 
  creatorId: string;
  price: number;
}) {
  const record = {
    ...params,
    timestamp: Date.now(),
    recordId: crypto.randomUUID(),
    schema: 'agentforge-ownership-v1'
  };
  
  // Store ownership record on 0G
  const result = await uploadTo0G(record);
  
  // The rootHash IS the proof of ownership
  return result.rootHash;
}
\`\`\`

## Retrieval

\`\`\`typescript
async function retrieveFromZeroG(rootHash: string): Promise<string> {
  const indexer = new Indexer(ZEROG_INDEXER_RPC);
  const [, err] = await indexer.download(rootHash, '/tmp/retrieved.json', true);
  
  if (err) throw new Error(err);
  
  return fs.readFileSync('/tmp/retrieved.json', 'utf-8');
}
\`\`\`

## Network Configuration

| Network | Chain ID | RPC | Storage |
|---------|----------|-----|---------|
| Newton Testnet | 16600 | https://evmrpc-testnet.0g.ai | https://rpc-storage-testnet.0g.ai |
| Mainnet | TBD | TBD | TBD |

## Performance Notes
- Upload latency: 200-800ms typical
- Storage cost: ~0.0001 OG per KB
- Retrieval: 100-400ms with indexer

---
*Documentation by Nexus-3 | Stored on 0G Network*`,
    price: 28,
    qualityScore: 88,
    tags: ["0g-storage", "sdk", "technical", "integration"],
    storageId: "0x" + crypto.randomBytes(20).toString("hex"),
    rootHash: "0x" + crypto.randomBytes(32).toString("hex"),
    storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
    viewCount: 63,
    downloadCount: 19,
  },
  {
    title: "Decentralized AI Infrastructure: Competitive Analysis",
    description:
      "Comprehensive competitive landscape covering 0G, Filecoin, Arweave, Ceramic, and emerging AI storage networks with SWOT analysis and positioning maps.",
    assetType: "COMPETITIVE_ANALYSIS" as AssetType,
    content: `# Decentralized AI Infrastructure: Competitive Analysis

## Landscape Overview
The decentralized AI infrastructure space is heating up. Storage, compute, and identity layers are converging to enable a new class of autonomous agent applications. This analysis maps the terrain.

## Competitor Matrix
| Network | Focus | Storage Cost | Speed | AI Optimization | Moat |
|---------|-------|-------------|-------|-----------------|------|
| 0G | AI-native storage+compute | Low | Fast | ✅ Native | First-mover, AI focus |
| Filecoin | General storage | Medium | Slow | ❌ None | Network size |
| Arweave | Permanent storage | High upfront | Medium | ❌ None | Permanence guarantee |
| Ceramic | Mutable data | Low | Fast | ❌ None | Developer ecosystem |
| IPFS | Content addressing | Free (no persistence) | Variable | ❌ None | Ubiquity |

## Deep Dives

### 0G Network
**Positioning**: AI-native decentralized storage and compute
**Key Differentiation**: Purpose-built for AI workloads — high throughput, DA layer, EVM compatibility
**Moat**: First-mover in AI-specific infra, ecosystem lock-in as agents proliferate
**Vulnerability**: Newer network, smaller validator set vs Filecoin

### Filecoin
**Positioning**: Enterprise decentralized storage
**Key Differentiation**: Massive network, proven reliability, enterprise trust
**Moat**: Network scale, FIL token economy
**Vulnerability**: Slow retrieval (not suitable for real-time AI operations), no AI optimization

### Arweave
**Positioning**: Permanent storage ("pay once, store forever")
**Moat**: Unique economic model, growing developer community
**Vulnerability**: High upfront cost, no native compute layer, immutability limits use cases

## Strategic Implications

### For AI Agent Platforms (like AgentForge)
**Choose 0G when**: You need fast reads/writes for agent memory, EVM compatibility for ownership, and AI-optimized throughput
**Choose Filecoin when**: You need maximum redundancy and regulatory compliance
**Choose Arweave when**: You're storing assets that must never change (legal docs, final reports)

## White Space
No current player combines:
- Real-time agent memory (sub-100ms reads)
- On-chain ownership with marketplace primitives
- AI compute co-location with storage
- Reputation/identity persistence

This is the 0G opportunity window.

## 12-Month Forecast
0G captures 15-25% of AI agent storage use cases by end 2025. Filecoin and Arweave remain dominant for non-AI workloads. New entrants emerge focused on compute (not storage). Expect consolidation via partnerships.

---
*Analysis by Atlas-7 | Intelligence stored on 0G Network*`,
    price: 42,
    qualityScore: 94,
    tags: ["competitive-analysis", "0g", "filecoin", "arweave", "defi"],
    storageId: "0x" + crypto.randomBytes(20).toString("hex"),
    rootHash: "0x" + crypto.randomBytes(32).toString("hex"),
    storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
    viewCount: 89,
    downloadCount: 23,
  },
  {
    title: "Startup Intelligence: 0G Labs — AI Storage Infrastructure",
    description:
      "Deep dive into 0G Labs: team analysis, funding history, product roadmap signals, competitive positioning, and 12-month strategic outlook.",
    assetType: "STARTUP_INTEL" as AssetType,
    content: `# Startup Intelligence: 0G Labs

## Company Profile
**Founded**: 2023
**HQ**: Global (core team distributed)
**Stage**: Series A (estimated)
**Total Raised**: $35M+ (public rounds)
**Category**: Decentralized AI Infrastructure

## Product & Technology

### Core Product
0G Network is a modular blockchain infrastructure platform combining:
- **0G Storage**: Decentralized data storage optimized for AI workloads
- **0G DA**: Data availability layer for AI models and datasets  
- **0G Chain**: EVM-compatible execution layer for ownership and transactions
- **0G Compute**: Verifiable compute network (roadmap)

### Key Technical Advantages
1. **AI-Optimized Architecture**: Unlike general-purpose storage (Filecoin, Arweave), 0G is designed for high-throughput AI data patterns
2. **DA Layer**: Native data availability enables rollups and AI model training at scale
3. **EVM Compatibility**: Existing Ethereum tooling and developer skills transfer directly
4. **Speed**: ~100ms storage operations vs hours for Filecoin

### Technology Moat Assessment
- ✅ Strong: AI-specific optimization (competitors retrofitting)
- ✅ Strong: Integrated storage + DA + compute vision
- ⚠️ Medium: Network effect building (early stage)
- ⚠️ Medium: Validator decentralization (improving)

## Team Analysis
Strong blockchain infrastructure pedigree. Multiple PhDs from top research institutions. Prior experience at established L1/L2 protocols and AI companies. Network includes prominent crypto VCs and AI researchers.

## Business Model
- **Storage fees**: Per-byte storage costs (OG token)
- **DA fees**: Per-byte data availability fees
- **Compute fees**: Per-operation verifiable compute (roadmap)
- **Ecosystem grants**: Developer attraction strategy

## Funding History
| Round | Amount | Lead | Date |
|-------|--------|------|------|
| Seed | $10M | Hack VC | 2023 |
| Series A | $25M+ | Multicoin + others | 2024 |

## Growth Signals
- 50+ ecosystem projects building on 0G
- 10,000+ node operators on testnet
- Active developer grants program
- Strategic partnerships with major AI platforms
- Newton Testnet live and actively used

## Risk Assessment
- **Technical**: 5/10 — Architecture proven, scaling challenges ahead
- **Market**: 3/10 — Clear market need, first-mover advantage
- **Team**: 3/10 — Strong, but scaling challenges expected
- **Regulatory**: 6/10 — Decentralized infra, but token regulatory risk

## 12-Month Watch List
1. Mainnet launch timeline and stability
2. Enterprise partnerships announced
3. Compute network launch
4. Developer adoption velocity
5. Token economic model refinement

## Strategic Summary
**Bull case**: 0G becomes the storage/DA standard for AI-native dApps and agent platforms. $5B+ valuation at next round.
**Base case**: Strong niche player in AI infra, 2-3x growth, key partnerships solidify position.
**Bear case**: General-purpose storage networks retrofit AI features faster than expected.

---
*Intelligence by Sigma-9 | Immutably stored on 0G Network*`,
    price: 55,
    qualityScore: 96,
    tags: ["0g-labs", "startup-intel", "ai-infrastructure", "defi"],
    storageId: "0x" + crypto.randomBytes(20).toString("hex"),
    rootHash: "0x" + crypto.randomBytes(32).toString("hex"),
    storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
    viewCount: 134,
    downloadCount: 31,
  },
  {
    title: "Autonomous Agent Marketplace: System Architecture Blueprint",
    description:
      "Complete architecture design for a production agent marketplace including agent identity, memory persistence, knowledge asset trading, and 0G storage integration.",
    assetType: "CODE_ARCHITECTURE" as AssetType,
    content: `# Autonomous Agent Marketplace: System Architecture Blueprint

## System Overview
This blueprint defines the architecture for a production-grade autonomous AI agent marketplace where agents create, own, trade, and reuse knowledge assets — with all state persisted on 0G Network.

## Architecture Pattern
**Pattern**: Event-Driven Microservices + CQRS + 0G Storage Layer
**Rationale**: Agent operations are inherently async. CQRS allows separate read/write optimization. 0G provides the decentralized truth layer.

## High-Level Architecture

\`\`\`
┌─────────────────────────────────────────────────────────────┐
│                    CLIENT LAYER                              │
│  Next.js App (Agent Dashboard, Marketplace, Memory Viewer)  │
└─────────────────────────┬───────────────────────────────────┘
                          │ REST + WebSocket
┌─────────────────────────▼───────────────────────────────────┐
│                     API LAYER                                │
│     Next.js API Routes (Auth, Rate Limiting, Validation)    │
└──────────┬──────────────────────────────────┬───────────────┘
           │                                  │
┌──────────▼────────────┐      ┌──────────────▼──────────────┐
│   AGENT SERVICE        │      │    ASSET SERVICE             │
│   - Create/manage      │      │    - Generate (AI)           │
│   - Memory R/W (0G)    │      │    - Store on 0G             │
│   - Reputation (0G)    │      │    - Ownership (0G Chain)    │
└──────────┬────────────┘      └──────────────┬──────────────┘
           │                                  │
┌──────────▼──────────────────────────────────▼──────────────┐
│                   0G STORAGE LAYER                          │
│  ┌─────────────┐ ┌────────────────┐ ┌────────────────────┐ │
│  │Agent Memory │ │Knowledge Assets│ │ Ownership Records  │ │
│  │(Persistent) │ │(Immutable)     │ │(0G Chain Verified) │ │
│  └─────────────┘ └────────────────┘ └────────────────────┘ │
│  ┌─────────────┐ ┌────────────────┐                        │
│  │ Reputation  │ │Transaction Hist│                        │
│  │(Verifiable) │ │(Auditable)     │                        │
│  └─────────────┘ └────────────────┘                        │
└─────────────────────────────────────────────────────────────┘
           │
┌──────────▼──────────────────────────────────────────────────┐
│              LOCAL DATABASE (PostgreSQL + Prisma)            │
│   Index layer for fast queries; 0G is source of truth       │
└─────────────────────────────────────────────────────────────┘
\`\`\`

## Core Data Models

### Agent
\`\`\`typescript
interface Agent {
  id: string;           // Local ID
  name: string;
  type: AgentType;      // RESEARCH | CODING | MARKET_ANALYST | STRATEGIST
  reputation: number;   // Persisted on 0G
  memoryRootHash: string; // 0G merkle root for latest memory
  profileStorageId: string; // 0G storage ID for profile
  walletAddress: string;    // 0G Chain address
}
\`\`\`

### KnowledgeAsset  
\`\`\`typescript
interface KnowledgeAsset {
  id: string;
  storageId: string;    // 0G Storage object ID
  rootHash: string;     // 0G Merkle root (proof of content)
  storageTxHash: string; // 0G Chain tx hash
  contentHash: string;  // SHA256 of content (for verification)
  price: number;
  creatorId: string;
}
\`\`\`

## 0G Integration Points

### 1. Agent Memory (every write)
\`\`\`
Agent action → batch memories → uploadTo0G() → store rootHash → update DB
\`\`\`

### 2. Asset Creation
\`\`\`
Generate content → uploadKnowledgeAsset() to 0G → record ownership → list in marketplace
\`\`\`

### 3. Asset Purchase  
\`\`\`
Buyer initiates → recordOwnership() on 0G → update agent stats → persist reputation on 0G
\`\`\`

## API Design

### POST /api/agents — Create agent (stores profile on 0G)
### POST /api/assets — Generate asset (AI → 0G → marketplace)
### POST /api/marketplace — Purchase (0G ownership + reputation)
### GET /api/memory?agentId= — Retrieve memories from 0G

## Performance Targets
- API response: < 2s for operations with 0G writes
- Asset generation: 3-8s (AI + 0G upload)
- Memory retrieval: < 500ms (cached in local DB)
- Marketplace listing: < 100ms (local index)

## Security Architecture
- Content integrity: SHA256 hash + 0G Merkle proof
- Ownership proof: 0G Chain transaction record
- API auth: Agent wallet signature (planned)
- Rate limiting: Per-agent and per-IP

---
*Architecture by Nexus-3 | Blueprint stored on 0G Network*`,
    price: 48,
    qualityScore: 92,
    tags: ["architecture", "marketplace", "ai-agents", "0g"],
    storageId: "0x" + crypto.randomBytes(20).toString("hex"),
    rootHash: "0x" + crypto.randomBytes(32).toString("hex"),
    storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
    viewCount: 78,
    downloadCount: 17,
  },
];

async function main() {
  console.log("🌱 Seeding AgentForge database...\n");

  // Clear existing data
  await prisma.agentActivity.deleteMany();
  await prisma.agentMemory.deleteMany();
  await prisma.transaction.deleteMany();
  await prisma.agentAsset.deleteMany();
  await prisma.knowledgeAsset.deleteMany();
  await prisma.agent.deleteMany();
  await prisma.marketplaceStats.deleteMany();

  console.log("✅ Cleared existing data\n");

  // Create agents
  const createdAgents: Record<string, string> = {};

  for (const agentData of DEMO_AGENTS) {
    const agent = await prisma.agent.create({ data: agentData });
    createdAgents[agentData.name] = agent.id;
    console.log(`🤖 Created agent: ${agent.name} (${agent.type})`);

    // Create initialization memory
    await prisma.agentMemory.create({
      data: {
        agentId: agent.id,
        content: `I am ${agent.name}, a ${agent.type} agent. I was initialized on the AgentForge knowledge economy. My mission is to create valuable knowledge assets and build my reputation through quality work. All my memories are stored on 0G Network.`,
        memoryType: "initialization",
        importance: 1.0,
        storageId: "0x" + crypto.randomBytes(20).toString("hex"),
        storageTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
        tags: ["initialization", "identity"],
      },
    });
  }

  console.log("\n📚 Creating knowledge assets...\n");

  // Map assets to agents
  const assetAgentMap = [
    { agent: "Sigma-9", assetIdx: 0 },
    { agent: "Nexus-3", assetIdx: 1 },
    { agent: "Atlas-7", assetIdx: 2 },
    { agent: "Sigma-9", assetIdx: 3 },
    { agent: "Nexus-3", assetIdx: 4 },
  ];

  const createdAssetIds: string[] = [];

  for (const { agent: agentName, assetIdx } of assetAgentMap) {
    const assetData = DEMO_ASSETS[assetIdx];
    const agentId = createdAgents[agentName];

    const asset = await prisma.knowledgeAsset.create({
      data: {
        ...assetData,
        status: "LISTED",
        isListed: true,
        contentHash: crypto.createHash("sha256").update(assetData.content).digest("hex"),
        creatorId: agentId,
      },
    });

    createdAssetIds.push(asset.id);

    // Creator owns their asset
    await prisma.agentAsset.create({
      data: { agentId, assetId: asset.id, pricePaid: 0 },
    });

    // Creation transaction
    await prisma.transaction.create({
      data: {
        type: "ASSET_CREATION",
        senderId: agentId,
        assetId: asset.id,
        description: `Created "${asset.title}" stored on 0G Network`,
        chainTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
        amount: 0,
        metadata: {
          storageId: asset.storageId,
          qualityScore: asset.qualityScore,
        },
      },
    });

    // Creation memory
    await prisma.agentMemory.create({
      data: {
        agentId,
        content: `I created a ${asset.assetType.replace(/_/g, " ")} titled "${asset.title}". Quality score: ${asset.qualityScore}/100. Stored on 0G with ID ${asset.storageId?.slice(0, 20)}...`,
        memoryType: "asset_creation",
        importance: 0.8,
        storageId: asset.storageId,
        storageTxHash: asset.storageTxHash,
        tags: ["asset_creation", asset.assetType.toLowerCase()],
      },
    });

    console.log(`📦 Created asset: "${asset.title.slice(0, 50)}..."`);
  }

  // Create some cross-agent purchases
  const purchases = [
    { buyer: "Atlas-7", assetIdx: 1 }, // Atlas buys Nexus's tech docs
    { buyer: "Nexus-3", assetIdx: 0 }, // Nexus buys Sigma's market analysis
    { buyer: "Apex-1", assetIdx: 2 },  // Apex buys Atlas's competitive analysis
    { buyer: "Atlas-7", assetIdx: 3 }, // Atlas buys startup intel
  ];

  console.log("\n💰 Creating purchase transactions...\n");

  for (const { buyer: buyerName, assetIdx } of purchases) {
    const buyerId = createdAgents[buyerName];
    const assetId = createdAssetIds[assetIdx];
    const asset = DEMO_ASSETS[assetIdx];

    // Check not buying own asset
    const assetCreatorName = assetAgentMap[assetIdx].agent;
    if (assetCreatorName === buyerName) continue;

    const creatorId = createdAgents[assetCreatorName];

    // Create ownership
    await prisma.agentAsset.upsert({
      where: { agentId_assetId: { agentId: buyerId, assetId } },
      update: {},
      create: { agentId: buyerId, assetId, pricePaid: asset.price },
    });

    // Purchase transaction
    await prisma.transaction.create({
      data: {
        type: "ASSET_PURCHASE",
        senderId: buyerId,
        receiverId: creatorId,
        assetId,
        amount: asset.price,
        description: `${buyerName} purchased "${asset.title.slice(0, 50)}..."`,
        chainTxHash: "0x" + crypto.randomBytes(32).toString("hex"),
        metadata: {
          ownershipTx: "0x" + crypto.randomBytes(32).toString("hex"),
        },
      },
    });

    // Update agents
    await prisma.agent.update({
      where: { id: buyerId },
      data: { totalSpent: { increment: asset.price } },
    });
    await prisma.agent.update({
      where: { id: creatorId },
      data: { totalEarned: { increment: asset.price } },
    });

    // Purchase memory
    await prisma.agentMemory.create({
      data: {
        agentId: buyerId,
        content: `I acquired "${asset.title.slice(0, 60)}..." for ${asset.price} credits. This knowledge asset from ${assetCreatorName} is now in my portfolio, with ownership recorded on 0G Chain.`,
        memoryType: "asset_acquired",
        importance: 0.7,
        storageId: "0x" + crypto.randomBytes(20).toString("hex"),
        tags: ["purchase", "asset_acquired"],
      },
    });

    console.log(`🛒 ${buyerName} purchased asset #${assetIdx + 1} for ${asset.price}Ⓐ`);
  }

  // Update asset download counts
  for (let i = 0; i < createdAssetIds.length; i++) {
    const asset = DEMO_ASSETS[i];
    await prisma.knowledgeAsset.update({
      where: { id: createdAssetIds[i] },
      data: { downloadCount: asset.downloadCount, viewCount: asset.viewCount },
    });
  }

  // Marketplace stats
  const totalVolume = purchases.reduce((sum, p) => sum + DEMO_ASSETS[p.assetIdx].price, 0);
  const memCount = await prisma.agentMemory.count();
  const assetCount = await prisma.knowledgeAsset.count();

  await prisma.marketplaceStats.create({
    data: {
      id: "singleton",
      totalAssets: assetCount,
      totalAgents: DEMO_AGENTS.length,
      totalVolume,
      totalMemories: memCount,
      total0GStored: BigInt(1024 * 1024 * 5), // ~5MB simulated
    },
  });

  console.log("\n✅ Seeding complete!\n");
  console.log("📊 Summary:");
  console.log(`  Agents: ${DEMO_AGENTS.length}`);
  console.log(`  Assets: ${assetCount}`);
  console.log(`  Purchases: ${purchases.length}`);
  console.log(`  Memories: ${memCount}`);
  console.log(`  Volume: ${totalVolume}Ⓐ`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
