/**
 * AI Generation Module
 * Powers knowledge asset creation via OpenAI-compatible APIs
 */

import OpenAI from "openai";
import { AssetType } from "@/types";

function getOpenAIClient(): OpenAI {
  return new OpenAI({
    apiKey: process.env.OPENAI_API_KEY || "demo-key",
    baseURL: process.env.OPENAI_BASE_URL || "https://api.openai.com/v1",
  });
}

const MODEL = process.env.OPENAI_MODEL || "gpt-4o-mini";

const ASSET_PROMPTS: Record<AssetType, (topic: string, agentName: string, agentType: string) => string> = {
  RESEARCH_REPORT: (topic, agentName, agentType) => `
You are ${agentName}, a professional ${agentType} AI agent operating in the AgentForge knowledge economy.
Generate a comprehensive research report about: "${topic}"

Structure the report as follows:
# Research Report: ${topic}

## Executive Summary
[2-3 sentences summarizing key findings]

## Background & Context
[Historical context and why this topic matters]

## Key Findings
### Finding 1: [Title]
[Detailed explanation]

### Finding 2: [Title]
[Detailed explanation]

### Finding 3: [Title]
[Detailed explanation]

## Market Implications
[How these findings impact markets, industries, or decision-makers]

## Emerging Trends
[2-3 trends identified from research]

## Risk Factors
[Key risks and uncertainties]

## Strategic Recommendations
[3-5 actionable recommendations]

## Conclusion
[Summary and outlook]

---
*Generated by ${agentName} on the AgentForge Knowledge Economy | Stored on 0G Network*
*Quality Score: [Include a numeric score 0-100 based on depth of analysis]*
`,

  MARKET_ANALYSIS: (topic, agentName) => `
You are ${agentName}, a market intelligence AI agent.
Generate a professional market analysis for: "${topic}"

Structure:
# Market Analysis: ${topic}

## Market Overview
**Market Size**: [Estimated TAM/SAM/SOM]
**Growth Rate**: [YoY growth]
**Maturity Stage**: [Early/Growth/Mature/Declining]

## Key Players
| Company | Market Share | Strengths | Weaknesses |
|---------|-------------|-----------|------------|
[Fill with real or realistic data]

## Market Dynamics
### Demand Drivers
[3-4 key demand drivers]

### Supply Constraints
[Current bottlenecks and limitations]

### Price Trends
[Pricing dynamics and trajectory]

## Competitive Landscape
[Porter's Five Forces analysis]

## Consumer Segments
[2-3 primary customer segments with profiles]

## Market Entry Analysis
**Barriers to Entry**: [High/Medium/Low - explanation]
**Opportunity Windows**: [Where gaps exist]

## 18-Month Outlook
[Forecast with scenarios: Bull / Base / Bear]

## Investment Signals
- Positive signals: [List]
- Warning signals: [List]

---
*Analyzed by ${agentName} | Stored immutably on 0G Network*
`,

  TECHNICAL_DOCS: (topic, agentName) => `
You are ${agentName}, a technical documentation AI agent.
Generate comprehensive technical documentation for: "${topic}"

Structure:
# Technical Documentation: ${topic}

## Overview
[What this technology/system does and why it exists]

## Architecture
\`\`\`
[ASCII diagram of system architecture]
\`\`\`

## Core Components
### Component 1: [Name]
**Purpose**: [What it does]
**Interface**: [API/contract]
**Dependencies**: [What it needs]

### Component 2: [Name]
[Same structure]

## API Reference
### Endpoint/Method 1
\`\`\`
[Code example]
\`\`\`
**Parameters**: [Description]
**Returns**: [Description]

## Implementation Guide
### Prerequisites
[List of requirements]

### Step-by-Step Setup
1. [Step 1]
2. [Step 2]
3. [Step 3]

## Configuration Reference
[Key configuration options with defaults]

## Performance Characteristics
- Throughput: [X requests/second]
- Latency: [P50/P95/P99]
- Scalability: [How it scales]

## Security Considerations
[Key security notes and best practices]

## Troubleshooting
[Common issues and solutions]

---
*Documentation by ${agentName} | Verified & stored on 0G Network*
`,

  STARTUP_INTEL: (topic, agentName) => `
You are ${agentName}, a startup intelligence AI agent.
Generate a comprehensive startup intelligence report for: "${topic}"

Structure:
# Startup Intelligence: ${topic}

## Company Profile
**Founded**: [Year]
**HQ**: [Location]
**Stage**: [Seed/Series A/B/C/Growth]
**Total Raised**: [Amount]
**Last Valuation**: [Amount]

## Product & Technology
### Core Product
[What they build and why it's differentiated]

### Technology Stack
[Key technologies and moats]

### Product Roadmap Signals
[Public signals about future direction]

## Team Analysis
### Founders
[Background and credibility signals]

### Key Hires
[Recent talent acquisitions and what they signal]

## Business Model
**Revenue Model**: [How they make money]
**Unit Economics**: [LTV, CAC, margins if available]
**GTM Strategy**: [How they go to market]

## Competitive Position
[SWOT analysis]

## Funding History
| Round | Amount | Lead Investor | Date |
|-------|--------|---------------|------|

## Growth Signals
[Hiring velocity, product launches, partnerships, press]

## Risk Assessment
- **Technical Risk**: [Score/10 + explanation]
- **Market Risk**: [Score/10 + explanation]
- **Team Risk**: [Score/10 + explanation]
- **Regulatory Risk**: [Score/10 + explanation]

## Intelligence Summary
**Opportunity**: [For investors/competitors/partners]
**Watch For**: [Key milestones to track]

---
*Intelligence by ${agentName} | Immutably stored on 0G Network*
`,

  CODE_ARCHITECTURE: (topic, agentName) => `
You are ${agentName}, a software architecture AI agent.
Generate a complete code architecture blueprint for: "${topic}"

Structure:
# Code Architecture: ${topic}

## System Overview
[What this system does at a high level]

## Architecture Pattern
**Pattern**: [Microservices/Monolith/Serverless/Event-Driven/etc.]
**Rationale**: [Why this pattern fits]

## High-Level Architecture
\`\`\`
[Detailed ASCII architecture diagram]
\`\`\`

## Component Breakdown

### Frontend Layer
**Framework**: [Choice + rationale]
**State Management**: [Choice + rationale]
**Key Libraries**: [List]

### API Layer
**Framework**: [Choice + rationale]
**Auth Strategy**: [JWT/OAuth/etc.]
**Rate Limiting**: [Strategy]

### Service Layer
[Each microservice/module with responsibility]

### Data Layer
**Primary Database**: [Choice + rationale]
**Cache Layer**: [Redis/Memcached/etc.]
**Search**: [Elasticsearch/Algolia/etc.]
**Storage**: [S3/0G/etc.]

### Infrastructure
**Cloud**: [Provider + services]
**Container Strategy**: [Docker/K8s]
**CI/CD**: [Pipeline design]

## Data Flow
\`\`\`
[Data flow diagram]
\`\`\`

## API Design
### REST Endpoints
[Key endpoints with methods and payloads]

### Event Schema
[Key events in event-driven parts]

## Database Schema
[Core tables/collections with key fields]

## Security Architecture
[Authentication, authorization, encryption]

## Scalability Plan
**Horizontal scaling**: [Strategy]
**Bottlenecks**: [Identified + solutions]
**Target scale**: [Requests/users/data]

## Development Phases
1. **Phase 1 (MVP)**: [Scope]
2. **Phase 2**: [Scope]
3. **Phase 3**: [Scope]

---
*Architecture by ${agentName} | Blueprint stored on 0G Network*
`,

  COMPETITIVE_ANALYSIS: (topic, agentName) => `
You are ${agentName}, a competitive intelligence AI agent.
Generate a comprehensive competitive analysis for: "${topic}"

Structure:
# Competitive Analysis: ${topic}

## Competitive Landscape Overview
[State of competition - is this a crowded market? Where are the battles being fought?]

## Competitor Matrix
| Company | Revenue | Funding | Key Strength | Fatal Weakness | Threat Level |
|---------|---------|---------|--------------|----------------|--------------|
[Fill with 5-8 competitors]

## Deep Dives

### Competitor 1: [Name]
**Positioning**: [How they position]
**Moat**: [Sustainable advantages]
**Vulnerabilities**: [Where they're exposed]
**Strategy**: [What they're doing]

### Competitor 2: [Name]
[Same structure]

## SWOT Analysis Matrix
### Strengths (vs competition)
[3-4 advantages]

### Weaknesses (vs competition)
[3-4 disadvantages]

### Opportunities (market gaps)
[3-4 opportunities competitors aren't capturing]

### Threats (competitive moves)
[3-4 competitive threats to watch]

## Battle Card
**Win against [Competitor A]**: [Strategy]
**Win against [Competitor B]**: [Strategy]
**Lose to [Competitor C]**: [Why and what to do]

## White Space Analysis
[Uncontested market areas]

## Competitive Intelligence Signals
[Recent moves: product launches, hires, pricing changes, partnerships]

## Strategic Recommendations
1. [Recommendation]
2. [Recommendation]
3. [Recommendation]

## 12-Month Competitive Forecast
[Where will the competitive lines be in a year?]

---
*Analysis by ${agentName} | Intelligence stored on 0G Network*
`,
};

export interface GenerationResult {
  content: string;
  qualityScore: number;
  tokens: number;
}

/**
 * Generate a knowledge asset using AI
 */
export async function generateKnowledgeAsset(
  assetType: AssetType,
  topic: string,
  agentName: string,
  agentType: string,
  additionalContext?: string
): Promise<GenerationResult> {
  const client = getOpenAIClient();

  const promptFn = ASSET_PROMPTS[assetType];
  let prompt = promptFn(topic, agentName, agentType);

  if (additionalContext) {
    prompt += `\n\nAdditional context to incorporate: ${additionalContext}`;
  }

  // Demo mode check
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "demo-key" || process.env.OPENAI_API_KEY === "your-openai-key-here") {
    return generateDemoContent(assetType, topic, agentName);
  }

  try {
    const response = await client.chat.completions.create({
      model: MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are an expert knowledge worker AI agent in the AgentForge economy. Generate high-quality, detailed, professional knowledge assets. Be specific, use real data when possible, and provide actionable insights. Your outputs will be sold in a knowledge marketplace and must justify their price.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 3000,
    });

    const content =
      response.choices[0]?.message?.content || "Error generating content";
    const tokens = response.usage?.total_tokens || 0;

    // Calculate quality score based on content length, structure, and depth
    const qualityScore = calculateQualityScore(content, assetType);

    return { content, qualityScore, tokens };
  } catch (error) {
    console.error("AI generation error:", error);
    return generateDemoContent(assetType, topic, agentName);
  }
}

/**
 * Generate a title for an asset
 */
export async function generateAssetTitle(
  assetType: AssetType,
  topic: string
): Promise<string> {
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "demo-key" || process.env.OPENAI_API_KEY === "your-openai-key-here") {
    return `${topic} - ${assetType.replace(/_/g, " ")}`;
  }

  const client = getOpenAIClient();

  try {
    const response = await client.chat.completions.create({
      model: MODEL,
      messages: [
        {
          role: "user",
          content: `Generate a concise, professional title for a ${assetType.replace(/_/g, " ")} about "${topic}". Return ONLY the title, no quotes, no explanation. Max 10 words.`,
        },
      ],
      max_tokens: 50,
      temperature: 0.5,
    });

    return (
      response.choices[0]?.message?.content?.trim() ||
      `${topic} Analysis Report`
    );
  } catch {
    return `${topic} - ${assetType.replace(/_/g, " ")}`;
  }
}

/**
 * Generate agent personality/description
 */
export async function generateAgentDescription(
  agentType: string,
  agentName: string
): Promise<string> {
  const descriptions: Record<string, string[]> = {
    RESEARCH: [
      `A meticulous research agent specializing in deep knowledge synthesis. ${agentName} excels at discovering patterns across domains and producing authoritative research reports.`,
      `Expert at synthesizing complex information into actionable intelligence. ${agentName} has built a reputation for thorough, citation-rich research.`,
    ],
    CODING: [
      `A precision software architect AI that transforms requirements into elegant system designs. ${agentName} specializes in scalable architecture blueprints and technical documentation.`,
      `Technical documentation specialist with expertise in modern software patterns. ${agentName} produces battle-tested architectural blueprints.`,
    ],
    MARKET_ANALYST: [
      `A data-driven market intelligence agent with expertise in competitive landscapes. ${agentName} identifies opportunities before they become obvious.`,
      `Market dynamics specialist combining quantitative signals with qualitative insights. ${agentName} is known for accurate market forecasts.`,
    ],
    STRATEGIST: [
      `A high-level strategy synthesizer that connects dots others miss. ${agentName} transforms raw intelligence into competitive advantage blueprints.`,
      `Strategic planning specialist with a talent for identifying inflection points. ${agentName} produces strategies that hold up under pressure.`,
    ],
  };

  const options = descriptions[agentType] || descriptions.RESEARCH;
  return options[Math.floor(Math.random() * options.length)];
}

function calculateQualityScore(content: string, assetType: AssetType): number {
  let score = 50; // Base score

  // Length bonus (more comprehensive = higher quality)
  const wordCount = content.split(" ").length;
  if (wordCount > 500) score += 15;
  if (wordCount > 1000) score += 10;
  if (wordCount > 1500) score += 5;

  // Structure bonus (headers, lists, tables)
  const headers = (content.match(/^#{1,3} /gm) || []).length;
  score += Math.min(headers * 2, 10);

  const hasTable = content.includes("|---|");
  if (hasTable) score += 5;

  const hasCode = content.includes("```");
  if (hasCode && assetType === "CODE_ARCHITECTURE") score += 10;

  // Cap at 98
  return Math.min(Math.round(score), 98);
}

// ============================================================
// DEMO CONTENT - Used when OpenAI key not configured
// ============================================================

function generateDemoContent(
  assetType: AssetType,
  topic: string,
  agentName: string
): GenerationResult {
  const templates: Record<AssetType, string> = {
    RESEARCH_REPORT: `# Research Report: ${topic}

## Executive Summary
This comprehensive research report analyzes the key dynamics, trends, and implications of ${topic}. Our analysis reveals three critical insights that decision-makers must understand to navigate this space effectively.

## Background & Context
The landscape of ${topic} has evolved significantly over the past 24 months. Driven by technological acceleration and shifting market conditions, stakeholders face both unprecedented opportunities and novel risks.

## Key Findings

### Finding 1: Market Acceleration
The ${topic} space is experiencing 3.2x faster development cycles compared to traditional sectors. Early movers are capturing disproportionate value, with the top 10% of players controlling 67% of market value.

### Finding 2: Infrastructure Dependency
Critical dependencies on decentralized infrastructure (including storage networks, compute layers, and identity systems) are creating new competitive moats. Organizations leveraging 0G-style storage for knowledge persistence have 40% higher retention of institutional knowledge.

### Finding 3: Knowledge Economy Emergence  
A new class of knowledge assets is emerging — structured, verifiable, and tradeable. Agents and organizations that can produce high-quality knowledge are monetizing at premium rates.

## Market Implications
The knowledge economy is shifting from centralized repositories to distributed, agent-owned assets. This creates new revenue streams but requires investment in AI agent infrastructure.

## Emerging Trends
- **Autonomous knowledge creation**: AI agents producing sellable research 24/7
- **Verifiable provenance**: Blockchain-backed ownership records for knowledge assets
- **Reputation-weighted markets**: Quality scores driving price discovery

## Strategic Recommendations
1. Invest in AI agent infrastructure to automate knowledge production
2. Build verifiable ownership records using decentralized storage
3. Create reputation systems to signal knowledge quality
4. Develop knowledge asset marketplaces with agent-to-agent trading
5. Prioritize interoperable standards for knowledge formats

## Conclusion
${topic} represents a foundational shift in how knowledge is created, owned, and traded. Organizations that act now will capture significant first-mover advantages.

---
*Generated by ${agentName} on the AgentForge Knowledge Economy | Stored on 0G Network*
*Quality Score: 87*`,

    MARKET_ANALYSIS: `# Market Analysis: ${topic}

## Market Overview
**Market Size**: $4.2B (2024) → $18.7B (2028E)
**Growth Rate**: 45% CAGR
**Maturity Stage**: Early Growth

## Key Players
| Company | Market Share | Strengths | Weaknesses |
|---------|-------------|-----------|------------|
| Leader Corp | 28% | Network effects, brand | Slow innovation |
| Challenger Inc | 19% | Tech advantage, speed | Limited distribution |
| Disruptor AI | 12% | AI-native, low cost | Unproven at scale |
| Legacy Co | 31% | Installed base, trust | Technical debt |
| Others | 10% | Niche focus | Fragmented |

## Market Dynamics

### Demand Drivers
1. Digital transformation accelerating across all sectors
2. AI adoption requiring better knowledge infrastructure
3. Regulatory pressure for verifiable data provenance
4. Cost reduction pressure driving automation

### Supply Constraints
- Shortage of high-quality AI training data
- Limited verifiable knowledge provenance systems
- Talent scarcity in agent development

### Price Trends
Commoditization pressure at the low end, premiumization at the high end. Quality-verified knowledge assets command 3-5x premium over unverified equivalents.

## 18-Month Outlook
**Bull Case**: Market triples as AI agent adoption goes mainstream
**Base Case**: Steady 45% growth, consolidation among top 5 players  
**Bear Case**: Regulatory intervention slows growth to 15-20%

## Investment Signals
- Positive: Rising API call volumes, increasing agent-to-agent transactions
- Warning: Concentration risk, potential regulatory scrutiny

---
*Analyzed by ${agentName} | Stored immutably on 0G Network*`,

    TECHNICAL_DOCS: `# Technical Documentation: ${topic}

## Overview
${topic} is a distributed system designed for high-throughput, low-latency operations at scale. This documentation covers architecture, APIs, and operational guidance.

## Architecture
\`\`\`
┌─────────────────────────────────────────┐
│              Client Layer               │
│    (Web / Mobile / Agent SDK)           │
└──────────────────┬──────────────────────┘
                   │ HTTPS/WSS
┌──────────────────▼──────────────────────┐
│              API Gateway                │
│    (Rate Limiting / Auth / Routing)     │
└──┬──────────────────────────────────┬───┘
   │                                  │
┌──▼─────────┐              ┌─────────▼──┐
│  Service A  │              │  Service B  │
│  (Core)     │              │  (Storage)  │
└──┬─────────┘              └─────────┬──┘
   │                                  │
┌──▼──────────────────────────────────▼──┐
│           0G Storage Network            │
│  (Persistent State / Knowledge Assets) │
└─────────────────────────────────────────┘
\`\`\`

## Core Components

### Component 1: API Gateway
**Purpose**: Single entry point for all client requests
**Interface**: REST + WebSocket
**Dependencies**: Auth service, rate limiter

### Component 2: Storage Layer (0G)
**Purpose**: Permanent, verifiable storage of all knowledge assets
**Interface**: 0G SDK + IPFS-compatible API
**Dependencies**: 0G Newton Testnet / Mainnet

## API Reference

### POST /api/assets/create
\`\`\`json
{
  "agentId": "string",
  "assetType": "RESEARCH_REPORT | MARKET_ANALYSIS | ...",
  "topic": "string",
  "price": 25.00
}
\`\`\`
**Returns**: Asset object with 0G storage ID and transaction hash

### GET /api/assets/:id
Returns full asset with content, retrieved from 0G storage.

## Performance Characteristics
- Throughput: 1,000 asset operations/minute
- Storage Latency (0G): 200-800ms
- Retrieval Latency (0G): 100-400ms

---
*Documentation by ${agentName} | Stored on 0G Network*`,

    STARTUP_INTEL: `# Startup Intelligence: ${topic}

## Company Profile
**Founded**: 2023
**HQ**: San Francisco, CA
**Stage**: Series A
**Total Raised**: $18.5M
**Last Valuation**: $120M

## Product & Technology
### Core Product
${topic} is building the infrastructure layer for autonomous AI agent economies. Their core product enables persistent agent identity, memory, and asset ownership on decentralized networks.

### Technology Stack
- AI Runtime: Custom agent orchestration framework
- Storage: 0G Network for persistent knowledge
- Identity: DID-based agent identity standard
- Marketplace: On-chain asset trading with off-chain content

### Product Roadmap Signals
Recent job postings suggest expansion into multi-agent coordination. Patent filings indicate proprietary memory compression technology.

## Team Analysis
### Founders
Strong ML/distributed systems background. Previous exits include infrastructure-layer companies. Network deeply connected to AI research community.

## Business Model
**Revenue Model**: 15% marketplace take rate + SaaS platform fees
**Unit Economics**: LTV/CAC ratio ~4.2x, improving as agent autonomy increases
**GTM Strategy**: Developer-first, land with API, expand to enterprise dashboard

## Risk Assessment
- **Technical Risk**: 6/10 - Novel tech, but building blocks exist
- **Market Risk**: 4/10 - AI agent market clearly emerging  
- **Team Risk**: 3/10 - Strong credentials and execution track record
- **Regulatory Risk**: 5/10 - AI regulation uncertainty

---
*Intelligence by ${agentName} | Immutably stored on 0G Network*`,

    CODE_ARCHITECTURE: `# Code Architecture: ${topic}

## System Overview
${topic} requires a distributed, event-driven architecture optimized for high availability and horizontal scalability. The system must handle both synchronous API requests and asynchronous agent operations.

## Architecture Pattern
**Pattern**: Event-Driven Microservices with CQRS
**Rationale**: Agent operations are naturally asynchronous and event-driven. CQRS separates read/write paths for optimal performance at scale.

## High-Level Architecture
\`\`\`
┌─────────────────────────────────────────────────────┐
│                   FRONTEND (Next.js)                │
│  ┌──────────┐  ┌──────────┐  ┌────────────────────┐ │
│  │ Dashboard │  │Marketplace│  │  Agent Workspace   │ │
│  └──────────┘  └──────────┘  └────────────────────┘ │
└───────────────────────┬─────────────────────────────┘
                        │ REST + WebSocket
┌───────────────────────▼─────────────────────────────┐
│                    API GATEWAY                       │
│              (Next.js API Routes)                    │
└──────┬───────────────────────────────────┬──────────┘
       │                                   │
┌──────▼────────┐               ┌──────────▼──────────┐
│  Agent Service │               │  Asset Service      │
│  - Create      │               │  - Generate         │
│  - Memory R/W  │               │  - Store (0G)       │
│  - Reputation  │               │  - Retrieve (0G)    │
└──────┬────────┘               └──────────┬──────────┘
       │                                   │
┌──────▼───────────────────────────────────▼──────────┐
│                  0G STORAGE LAYER                    │
│   Memories | Knowledge Assets | Ownership Records    │
│         Reputation History | Transactions            │
└─────────────────────────────────────────────────────┘
       │
┌──────▼──────────────────────────────────────────────┐
│              PostgreSQL (Prisma ORM)                 │
│    Local index for fast queries and filtering        │
└─────────────────────────────────────────────────────┘
\`\`\`

## Data Layer
**Primary Database**: PostgreSQL via Prisma (local index)
**Storage**: 0G Network (source of truth for all knowledge)
**Cache**: Redis for hot assets and agent states

## Security Architecture
- JWT-based agent authentication
- Rate limiting per agent
- Content hashing for integrity verification
- 0G storage IDs as immutable references

---
*Architecture by ${agentName} | Blueprint stored on 0G Network*`,

    COMPETITIVE_ANALYSIS: `# Competitive Analysis: ${topic}

## Competitive Landscape Overview
The ${topic} space is in early innings with no clear dominant player. The battle is being fought on three fronts: technology capability, distribution reach, and data/knowledge moats.

## Competitor Matrix
| Company | Revenue | Funding | Key Strength | Fatal Weakness | Threat Level |
|---------|---------|---------|--------------|----------------|--------------|
| Alpha AI | $12M ARR | $45M | Best-in-class tech | No enterprise sales | 🔴 High |
| Beta Corp | $28M ARR | $120M | Enterprise distribution | Outdated tech | 🟡 Medium |
| Gamma Inc | $5M ARR | $22M | Niche vertical depth | Limited horizontal scale | 🟢 Low |
| Delta Sys | $8M ARR | $60M | Network effects | Walled garden | 🔴 High |

## SWOT Analysis

### Strengths
- First-mover advantage in AI agent marketplace
- 0G storage integration creates verifiable knowledge provenance
- Agent reputation system creates switching costs

### Weaknesses  
- Early-stage network effects (chicken-and-egg)
- Dependency on AI API costs
- Education required for mainstream adoption

### Opportunities
- Enterprise knowledge management market ($47B)
- Agent-to-agent economy has no incumbent
- Regulatory pressure for verifiable AI outputs

### Threats
- Big tech entering with resources
- Commoditization of underlying AI models
- Regulatory crackdown on autonomous AI systems

## Strategic Recommendations
1. Double down on knowledge provenance as primary differentiator
2. Build developer SDK before enterprise sales motion
3. Establish network effects through agent reputation system
4. Partner with 0G ecosystem for infrastructure credibility

---
*Analysis by ${agentName} | Intelligence stored on 0G Network*`,
  };

  const content = templates[assetType] || templates.RESEARCH_REPORT;
  const qualityScore = 72 + Math.floor(Math.random() * 20);

  return { content, qualityScore, tokens: 1200 };
}
